In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

In [5]:
veri = pd.read_csv("telefon_fiyatlari.csv")
veri.info()
veri
#buradan tekrar yapıalcak

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Telefon kodu    11 non-null     object 
 1   RAM Kapasitesi  11 non-null     int64  
 2   Dahili hafiza   11 non-null     int64  
 3   Ekran Tipi      11 non-null     object 
 4   Fiyat           9 non-null      float64
dtypes: float64(1), int64(2), object(2)
memory usage: 568.0+ bytes


Telefon kodu  RAM Kapasitesi  Dahili hafiza    Ekran Tipi   Fiyat
0            T1               4            128  SUPER AMOLED  3300.0
1            T2               6            256        AMOLED  4400.0
2            T3               4            128        AMOLED  2700.0
3            T4               6            128           IPS  3600.0
4            T5               6             64           IPS  3200.0
5            T6               8            128  SUPER AMOLED  4100.0
6            T7               4             64        AMOLED  2400.0
7            T8               4             64  SUPER AMOLED  3000.0
8            T9               8            256           IPS  4200.0
9           T10               6            256           IPS     NaN
10          T11               8            128        AMOLED     NaN

In [7]:
veri["Ekran Tipi"].replace(to_replace=["SUPER AMOLED","AMOLED","IPS"],value=[3,2,1],inplace=True)
veri

Telefon kodu  RAM Kapasitesi  Dahili hafiza  Ekran Tipi   Fiyat
0            T1               4            128           3  3300.0
1            T2               6            256           2  4400.0
2            T3               4            128           2  2700.0
3            T4               6            128           1  3600.0
4            T5               6             64           1  3200.0
5            T6               8            128           3  4100.0
6            T7               4             64           2  2400.0
7            T8               4             64           3  3000.0
8            T9               8            256           1  4200.0
9           T10               6            256           1     NaN
10          T11               8            128           2     NaN

In [18]:
# 1- sklearn veri olarak numpy dizileri ile çalışır
# 2- Bu diziler 2 boyutlu olmalıdır
x_egitim=veri.iloc[0:9,1:4].values
y_egitim=veri.iloc[0:9,4].values.reshape(-1,1)
x_tahmin=veri.iloc[9:,1:4].values
x_tahmin

array([[  6, 256,   1],
       [  8, 128,   2]])

In [19]:
lr=LinearRegression()
lr.fit(x_egitim,y_egitim)

LinearRegression()

In [20]:
print("a,b,c",lr.coef_)
print("d",lr.intercept_)


a,b,c [[251.78571429   4.85491071 171.42857143]]
d [1035.71428571]


In [21]:
print(4*251.7+16*4.8+3*171.4+1035.7)

2633.5


In [22]:
lr.predict([[4,16,3]])

array([[2634.82142857]])

In [23]:
lr.predict(x_tahmin)

array([[3960.71428571],
       [4014.28571429]])